[RM.AR]
ExtractedEntity = files/excel/rm_extracted_entity.xlsx
ExtractedOccupant = files/excel/rm_extracted_occupant.xlsx
EntityMissingRecords = files/excel/rm_ar_missing_records_entity.xlsx
OccupantMissingRecords = files/excel/rm_ar_missing_records_occupant.xlsx
EntityTotals = files/excel/reportTotals/EntityTotals.xlsx
OccupantTotals = files/excel/reportTotals/OccupantTotals.xlsx
ComparisonResult = files/excel/comparison_results.xlsx
PDF = files/pdf/MRI_RMAGEDEL_0326_LIGHT4MC_full.pdf

[CM.ROLL]
ExtractedBuilding = files/excel/cm_extracted_bldg.xlsx
ExtractedSuites = files/excel/cm_extracted_suites.xlsx
ComparisonResult = files/excel/roll_comparison_results.xlsx
PDF = files/pdf/CM_RENT_ROLL_202505.pdf

[CM.LEDGER]
;PDF = files/pdf/LEDGERS_0525 1-US.pdf
;PDF = files/pdf/MRIX_LEDGER-Detailed 1-AUS.pdf
PDF = files/pdf/MRIX_LEDGRPT by Consolidated 20102025-AUS.pdf
LedgerTotals = files/excel/ledgers_totals_with_ids.xlsx
ReportExcel = files/excel/report/ledger_report_totals.xlsx
ComparisonResult = files/excel/ledger_comparison_results.xlsx

[CM.AGED]
TXT = files/Extracted.txt
;PDF = files/pdf/AGED_0525 1.pdf
PDF = files/pdf/Aged Deliquencies (Consol).pdf
OccupantTotals = files/excel/aged.xlsx
ReportExcel = files/excel/report/aged_report_totals.xlsx
ComparisonResult = files/excel/aged_comparison_results.xlsx